# Generated by Django 4.2.1 on 2023-06-16 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_rename_product_product1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartN',
        ),
    ]
